title: "Guía BluePill + STLINK"
description: "Guía práctica para debuggear microcontroladores ARM mediante SWD y OpenOCD."
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Modo oscuro automático
color_scheme: dark

# Sidebar y navegación
just_the_docs:
  logo: false
  search_enabled: true
  show_toc: true
  heading_anchors: true
  toc_label: "Índice"
  toc_levels: 1..4
