title: "Guía BluePill + STLINK"
description: "Guía práctica para debuggear microcontroladores ARM mediante SWD y OpenOCD."
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Modo oscuro automático
color_scheme: dark

# Sidebar y navegación
markdown: kramdown
kramdown:
  toc_levels: 2..4
